--CREATE DATABASE CigarShop

CREATE TABLE Sizes
(
	Id INT PRIMARY KEY IDENTITY,
	[Length] INT NOT NULL CHECK ([Length] BETWEEN 10 AND 25),
	RingRange DECIMAL(15,2) NOT NULL CHECK (RingRange BETWEEN 1.5 AND 7.5)
)
CREATE TABLE Tastes
(
	Id INT PRIMARY KEY IDENTITY,
	TasteType NVARCHAR(20) NOT NULL,
	TasteStrength NVARCHAR(15) NOT NULL,
	ImageURL NVARCHAR(100) NOT NULL
)
CREATE TABLE Brands
(
	Id INT PRIMARY KEY IDENTITY,
	BrandName NVARCHAR(30) NOT NULL UNIQUE,
	BrandDescription NVARCHAR(MAX)
)
CREATE TABLE Cigars
(
	Id INT PRIMARY KEY IDENTITY,
	CigarName NVARCHAR(80) NOT NULL,
	BrandId INT NOT NULL FOREIGN KEY (BrandId) REFERENCES Brands(Id),
	TastId INT NOT NULL FOREIGN KEY (TastId) REFERENCES Tastes(Id),
	SizeId INT NOT NULL FOREIGN KEY (SizeId) REFERENCES Sizes(Id),
	PriceForSingleCigar DECIMAL(15,2) NOT NULL,
	ImageURL NVARCHAR(100) NOT NULL
)
CREATE TABLE Addresses
(
	Id INT PRIMARY KEY IDENTITY,
	Town NVARCHAR(30) NOT NULL,
	Country NVARCHAR(30) NOT NULL,
	Streat NVARCHAR(100) NOT NULL,
	ZIP NVARCHAR(20) NOT NULL
)
CREATE TABLE Clients
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	AddressId INT NOT NULL FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
)
CREATE TABLE ClientsCigars
(
	ClientId INT NOT NULL FOREIGN KEY (ClientId) REFERENCES Clients(Id),
	CigarId INT NOT NULL FOREIGN KEY (CigarId) REFERENCES Cigars(Id),
	CONSTRAINT PK_ClientsCigars PRIMARY KEY (ClientId, CigarId)
)